AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'out/**/*'
    - 'bin/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6.2

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 20

Style/RedundantException:
  Enabled: false

Style/SymbolArray:
  Enabled: false
